### ISSUE TITLE
Audio decoding is *extremely* slow

### ISSUE THREAD

**Issue by ferjm** [servo/media#111]
This test case https://ferjm.github.io/web-api-tests/webaudio/decode.html takes ~465ms in Firefox vs ~40sec in Servo to start playing sound.

**Comment by philn** [comment]
Can you set the `sync` property to `false` for that element? https://github.com/servo/media/blob/master/backends/gstreamer/src/audio_decoder.rs#L104

**Comment by ferjm** [comment]
Yes! Setting the `sync` property to `false` makes the test start playing sound in ~250ms.
