### ISSUE TITLE
Build script link in Readme no longer works

### ISSUE THREAD

**Issue by atouchet** [servo/media#161]
https://github.com/servo/media/blob/master/backends/gstreamer/build.rs#L48 ("build script") returns a 404 as build.rs no longer exists.

**Comment by ferjm** [comment]
I removed the build script in #145

**Comment by atouchet** [comment]
@ferjm yes that's the issue. A link to that file is still in the Readme and no longer works.

**Comment by ferjm** [comment]
Hah, of course, I read it the other way around, sorry.

**Comment by ferjm** [comment]
https://github.com/servo/media/commit/e43b3b486ade4f0b636e01614b28c4e4f63001e6 

Sorry for the delay fixing this.
