### ISSUE TITLE
Full graph support

### ISSUE THREAD

**Issue by Manishearth** [servo/media#19]
Currently we just have a vector of nodes. We need the ability to have a full graph, using the cycle-breaking algorithm from the spec.

Probably should use petgraph.

**Comment by Manishearth** [comment]
Er, so I didn't notice you'd self-assigned this 😄 

Anyway, I cooked up a rough design.

We use [StableGraph](https://docs.rs/petgraph/0.4.12/petgraph/stable_graph/struct.StableGraph.html), as a directed graph.

The edge type is

```rust
struct Edge {
   n: u8, // edge number
   data: RefCell<Block>
}
```

Nodes are just `RefCell<Node>`s

Each time we process a node, we take the list of outgoing edges and split up the chunks into the `data` cache of each edge, with appropriate up/down mixing if necessary. We sort by `n`.

Then, when processing the next node, we pull the data out of the `data` cache and use it to assemble a `Chunk` which is passed down to the node.

We can also store the `data` cache out of band, it's just more annoying that way. But possible, since we'll need to store a worklist of nodes anyway.

Thoughts?

**Comment by Manishearth** [comment]
I'm also interested in hearing what your plans were for the design 😄 . There's a lot of stuff to tackle here.

(And, if you're working on this, what would you like me to work on? Channel support somewhat requires this to be figured out first)

**Comment by ferjm** [comment]
Oh, I self-assigned here to start looking at this after #38. I didn't have any plans yet and it seems that you already started the work here, so I'll reassign the issue to you.

Using the edges as data cache sounds good to me.

**Comment by ferjm** [comment]
#45 and #47 fixed this. We can track the remaining work in separated issues (i.e. #51 and #50)
