### ISSUE TITLE
New sink code isn't working

### ISSUE THREAD

**Issue by Manishearth** [servo/media#191]
When I try this I get a single frozen videosink, and this error in the logs:

```
0:00:00.650705511 29662 0x7f35a8004ad0 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<nicesrc3> error: Internal data stream error.
0:00:00.650721783 29662 0x7f35a8004ad0 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<nicesrc3> error: streaming stopped, reason not-linked (-1)
0:00:00.907446112 29662 0x7f356048a6d0 WARN           basetransform gstbasetransform.c:1415:gst_base_transform_reconfigure:<videoconvert1> warning: not negotiated
0:00:00.907457873 29662 0x7f356048a6d0 WARN           basetransform gstbasetransform.c:1415:gst_base_transform_reconfigure:<videoconvert1> warning: not negotiated
0:00:00.956709545 29662 0x7f35bc02ee80 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<nicesrc0> error: Internal data stream error.
0:00:00.956748859 29662 0x7f35bc02ee80 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<nicesrc0> error: streaming stopped, reason not-negotiated (-4)
```

the "not linked" error is probably the relevant one, i suspect this cascades and breaks caps negotiation

the following patch which effectively reverts https://github.com/servo/media/pull/186 fixes the problem. I'm not sure what's going on here, they're almost equivalent.

```patch
diff --git a/backends/gstreamer/src/webrtc.rs b/backends/gstreamer/src/webrtc.rs
index eff0af7..e5df76f 100644
--- a/backends/gstreamer/src/webrtc.rs
+++ b/backends/gstreamer/src/webrtc.rs
@@ -268,11 +268,13 @@ fn handle_media_stream(
             let q = gst::ElementFactory::make("queue", None).unwrap();
             let conv = gst::ElementFactory::make("audioconvert", None).unwrap();
             let resample = gst::ElementFactory::make("audioresample", None).unwrap();
+            let sink = gst::ElementFactory::make("autoaudiosink", None).unwrap();
 
-            pipe.add_many(&[&q, &conv, &resample])?;
-            gst::Element::link_many(&[&q, &conv, &resample])?;
+            pipe.add_many(&[&q, &conv, &resample, &sink])?;
+            gst::Element::link_many(&[&q, &conv, &resample, &sink])?;
 
             resample.sync_state_with_parent()?;
+            sink.sync_state_with_parent()?;
 
             let elements = vec![q.clone(), conv.clone(), resample];
             (q, conv, elements)
@@ -280,9 +282,11 @@ fn handle_media_stream(
         StreamType::Video => {
             let q = gst::ElementFactory::make("queue", None).unwrap();
             let conv = gst::ElementFactory::make("videoconvert", None).unwrap();
+            let sink = gst::ElementFactory::make("autovideosink", None).unwrap();
 
-            pipe.add_many(&[&q, &conv])?;
-            gst::Element::link_many(&[&q, &conv])?;
+            pipe.add_many(&[&q, &conv, &sink])?;
+            gst::Element::link_many(&[&q, &conv, &sink])?;
+            sink.sync_state_with_parent()?;
 
             let elements = vec![q.clone(), conv.clone()];
             (q, conv, elements)
diff --git a/backends/gstreamer/src/media_stream.rs b/backends/gstreamer/src/media_stream.rs
index 0623e1f..867fd55 100644
--- a/backends/gstreamer/src/media_stream.rs
+++ b/backends/gstreamer/src/media_stream.rs
@@ -156,6 +156,7 @@ impl MediaSink {
 
 impl MediaOutput for MediaSink {
     fn add_stream(&mut self, stream: Box<MediaStream>) {
+        return;
         {
             let stream = stream.as_any().downcast_ref::<GStreamerMediaStream>().unwrap();
             let last_element = stream.elements.last();
```

**Comment by Manishearth** [comment]
I think this is because gstreamer expects there to be _some_ sink and will shut down source elements if there isn't. You can see this with `gst-launch-1.0 audiotestsrc`

**Comment by jdm** [comment]
What if we throw a fakesink on it when it's first created, then add_stream could unlink that and add the new sink instead?

**Comment by Manishearth** [comment]
That's what I'm playing with right now :)

**Comment by Manishearth** [comment]
Adding a queue element gets rid of the first error, but we still have the caps negotiation error.

I think we should only add the convert/resample elements when we're adding the sink, otherwise caps negotiation happens too early and I'm not sure how to retrigger it.

**Comment by Manishearth** [comment]
Even with resample/convrt elements on both sides it still fails to negotiate

**Comment by sdroege** [comment]
You need some kind of sink always, yes. Otherwise data will flow out of your elements into nothing, `gst::FlowError::NotLinked` is returned and things error out.

There's `fakesink` if you need a sink that does literally nothing. But why don't you always have a sink, when would the sink be added/removed?

**Comment by Manishearth** [comment]
We have a decodebin on the webrtc element that detects when a stream is added and attaches a sink in that case. The sink can be set up later so we need the ability to swap the sink here.

**Comment by sdroege** [comment]
You probably want a `tee` and a `fakesink` always then, and add/remove the other sinks dynamically from the `tee` when needed.

**Comment by Manishearth** [comment]
Will that lead to unnecessary copying when there are multiple sinks attached?

What about renegotiation? I tried using a queue and it would fail to negotiate caps, even if I attached a convert element after it on the other side.

**Comment by Manishearth** [comment]
Quickly tried it with a tee element, I no longer get link or renegotiation errors, but the autovideosinks aren't displaying

**Comment by sdroege** [comment]
> Will that lead to unnecessary copying when there are multiple sinks attached?

It depends but generally not. The `tee` is not copying but just increasing the reference count of the buffers.

> What about renegotiation? I tried using a queue and it would fail to negotiate caps, even if I attached a convert element after it on the other side.

Depends on the specific case :) Also why/how does it fail?

> Quickly tried it with a tee element, I no longer get link or renegotiation errors, but the autovideosinks aren't displaying

Do you have a `queue` after each source pad of the `tee`?

----

You can also dynamically replace the single sink, i.e. always have a `fakesink` and then switch to another sink when needed. You need to make use of pad probes for that to not disrupt the data flow.

**Comment by Manishearth** [comment]
I do now, it still isn't working:

i get these warnings but i don't think they're relevant

```
0:00:00.681598483   344 0x7fcb4c070ed0 WARN         audio-resampler audio-resampler.c:274:convert_taps_gint16_c: can't find exact taps
0:00:00.778869092   344 0x7fcbd002ef20 WARN         rtpjitterbuffer rtpjitterbuffer.c:570:calculate_skew: delta - skew: 0:00:01.017137845 too big, reset skew
0:00:01.020982305   344 0x7fcbc4004280 WARN            vaapidisplay gstvaapidisplay_wayland.c:167:gst_vaapi_display_wayland_bind_display: wayland: get display name

```

**Comment by Manishearth** [comment]
Here are my changes:

```rust
diff --git a/backends/gstreamer/src/media_stream.rs b/backends/gstreamer/src/media_stream.rs
index 0623e1f..6650c31 100644
--- a/backends/gstreamer/src/media_stream.rs
+++ b/backends/gstreamer/src/media_stream.rs
@@ -164,9 +164,11 @@ impl MediaOutput for MediaSink {
                 StreamType::Audio => "autoaudiosink",
                 StreamType::Video =>"autovideosink",
             };
+            let queue = gst::ElementFactory::make("queue", None).unwrap();
             let sink = gst::ElementFactory::make(sink, None).unwrap();
             stream.pipeline.as_ref().unwrap().add(&sink).unwrap();
-            gst::Element::link_many(&[last_element, &sink][..]).unwrap();
+            stream.pipeline.as_ref().unwrap().add(&queue).unwrap();
+            gst::Element::link_many(&[last_element, &queue, &sink][..]).unwrap();
 
             sink.sync_state_with_parent().unwrap();
         }
diff --git a/backends/gstreamer/src/webrtc.rs b/backends/gstreamer/src/webrtc.rs
index eff0af7..82dff49 100644
--- a/backends/gstreamer/src/webrtc.rs
+++ b/backends/gstreamer/src/webrtc.rs
@@ -263,32 +263,41 @@ fn handle_media_stream(
 ) -> Result<(), Box<Error>> {
     println!("Trying to handle stream {:?}", media_type);
 
-    let (q, conv, elements) = match media_type {
+    let (q, conv, tee, q2, sink, elements) = match media_type {
         StreamType::Audio => {
             let q = gst::ElementFactory::make("queue", None).unwrap();
             let conv = gst::ElementFactory::make("audioconvert", None).unwrap();
             let resample = gst::ElementFactory::make("audioresample", None).unwrap();
+            let tee = gst::ElementFactory::make("tee", None).unwrap();
+            let q2 = gst::ElementFactory::make("queue", None).unwrap();
+            let sink = gst::ElementFactory::make("fakesink", None).unwrap();
 
-            pipe.add_many(&[&q, &conv, &resample])?;
-            gst::Element::link_many(&[&q, &conv, &resample])?;
+            pipe.add_many(&[&q, &conv, &resample, &tee, &q2, &sink])?;
+            gst::Element::link_many(&[&q, &conv, &resample, &tee, &q2, &sink])?;
 
             resample.sync_state_with_parent()?;
 
-            let elements = vec![q.clone(), conv.clone(), resample];
-            (q, conv, elements)
+            let elements = vec![q.clone(), conv.clone(), resample, tee.clone()];
+            (q, conv, tee, q2, sink, elements)
         }
         StreamType::Video => {
             let q = gst::ElementFactory::make("queue", None).unwrap();
             let conv = gst::ElementFactory::make("videoconvert", None).unwrap();
+            let tee = gst::ElementFactory::make("tee", None).unwrap();
+            let q2 = gst::ElementFactory::make("queue", None).unwrap();
+            let sink = gst::ElementFactory::make("fakesink", None).unwrap();
 
-            pipe.add_many(&[&q, &conv])?;
-            gst::Element::link_many(&[&q, &conv])?;
+            pipe.add_many(&[&q, &conv, &tee, &q2, &sink])?;
+            gst::Element::link_many(&[&q, &conv, &tee, &q2, &sink])?;
 
-            let elements = vec![q.clone(), conv.clone()];
-            (q, conv, elements)
+            let elements = vec![q.clone(), conv.clone(), tee.clone()];
+            (q, conv, tee, q2, sink, elements)
         }
     };
     q.sync_state_with_parent()?;
+    q2.sync_state_with_parent()?;
+    tee.sync_state_with_parent()?;
+    sink.sync_state_with_parent()?;
     conv.sync_state_with_parent()?;
 
     let qpad = q.get_static_pad("sink").unwrap();
```

**Comment by jdm** [comment]
One warning I see which is probably related to ICE candidate gathering:
```
0:00:07.939087000 65740 0x7fd4337b9890 DEBUG              webrtcbin gstwebrtcbin.c:734:gst_webrtc_bin_enqueue_task:<sendrecv> Peerconnection is closed, aborting execution
```
The webrtcbin starts off closed until it moves to the READY state, which only happens once the first media stream has been added to it in our implementation.

**Comment by jdm** [comment]
Perhaps we could try setting it to READY on creation and then pausing it immediately.

**Comment by Manishearth** [comment]
Looks like the webkit impl uses a proxysrc and proxysink, which is pretty tempting as it lets us decouple the pipelines

https://github.com/WebKit/webkit/compare/master...philn:gstwebrtc#diff-2e3d7b4cd5f6fc9792616744354f5f6dR589

**Comment by nirbheek** [comment]
There two things you could try:

1. Output a pipeline graph with dot, see the docs for how to do that: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html. That should give a clearer picture of the pipeline state.

2. Uninstall/disable the vaapi elements, those are over-engineered and buggy. Best to use software encode/decode for now. Later, you will probably want to use nvdec/nvenc (which uses the nvidia video codec sdk) and the Intel MSDK (Media SDK) plugins for hardware decode/encode. Those have been tested on Windows and Linux, and will probably work on macOS too.

**Comment by sdroege** [comment]
>     1. Output a pipeline graph with dot, see the docs for how to do that: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html. That should give a clearer picture of the pipeline state.

See [here](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/a5a016557ff6c5aafcd58ecf6d2f3ed91ed2325a/gstreamer/src/bin.rs#L44-50) for the Rust API to do that.

>     2\. and will probably work on macOS too.

On macOS you also have the Apple `VideoToolkit` API that should work on all official Apple hardware (and there are GStreamer elements for that).

**Comment by Manishearth** [comment]
The webkit impl starts off with the state as READY, and I implemented that, however that doesn't fix the sink issue in itself (or the overall media issue). Might try some things again with queue or proxies.

**Comment by Manishearth** [comment]
I don't think I was getting these earlier, but I'm seeing these warnings:

```
** (servo:8195): WARNING **: 17:58:24.935: (gstwebrtcbin.c:1294):_create_transport_channel: code should not be reached

** (servo:8195): WARNING **: 17:58:24.936: (gstwebrtcbin.c:1300):_create_transport_channel: code should not be reached
```

which is basically the following code in the webrtc impl:

```
  if (!gst_element_link_pads (GST_ELEMENT (ret->receive_bin), "rtcp_src",
          GST_ELEMENT (webrtc->rtpbin), pad_name))
    g_warn_if_reached ();
  g_free (pad_name);

  pad_name = g_strdup_printf ("send_rtcp_src_%u", ret->session_id);
  if (!gst_element_link_pads (GST_ELEMENT (webrtc->rtpbin), pad_name,
          GST_ELEMENT (ret->send_bin), "rtcp_sink"))
    g_warn_if_reached ();
```

**Comment by Manishearth** [comment]
Okay, I've got `process_new_stream` working.

I think what I'm going to do is move the decodebin stuff to the media sink side, and have this directly output to a proxysink.

**Comment by Manishearth** [comment]
I've got a working fix. It uses proxysrc, but it probably doesn't need to (still, proxysrc is something we'll need later anyway, might as well use it now).

The issues were:

 - we shouldn't be vp8/opus encoding stuff going to the auto sinks
 - pipeline play state in webrtc was incorrect (and later: pipeline play state in my sink code was also broken)
 - decodebin was connected directly to the webrtc element instead of to its pad
 - the vaapi thing is broken

This does not fix the issue where servo-media doesn't see media streams attached by servo. I still will have to look into that.

**Comment by Manishearth** [comment]
Fixes are in https://github.com/servo/media/pull/208
