### ISSUE TITLE
Support constraints for media capture

### ISSUE THREAD

**Issue by jdm** [servo/media#192]
[This code](https://github.com/servo/media/blob/1e6618da825500049a73e5a586e41428f317e724/backends/gstreamer/src/media_capture.rs#L150-L170) creates a video or audio stream with default constraints. The [constraint API](https://github.com/servo/media/blob/1e6618da825500049a73e5a586e41428f317e724/backends/gstreamer/src/media_capture.rs#L76-L83) should be lifted out of the gstreamer backend into the [high level library](https://github.com/servo/media/blob/master/servo-media/src/lib.rs), so that it's possible for consumers of this crate to request an input stream that matches the given constraints. This will require adding additional arguments to the `create_videoinput_stream` and `create_audioinput_stream` functions and passing them down the stack until the `create_input_stream` method in the gstreamer backend.

**Comment by Manishearth** [comment]
I think the constraint API should live in servo-media-webrtc or a new crate, not servo-media itself (which should be a thin wrapper)

(a servo-media-streams crate may be useful, since we actually do need multiple backend implementations of streams)

**Comment by jdm** [comment]
That would be https://github.com/servo/media/blob/master/webrtc/src/lib.rs instead of https://github.com/servo/media/blob/master/servo-media/src/lib.rs, in that case.
