### ISSUE TITLE
Implement webrtc datachannel support

### ISSUE THREAD

**Issue by jdm** [servo/media#203]
Base gstreamer support exists in https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/tree/master/gstreamer-webrtc. We will want to generate new gstreamer-rs bindings for it in https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/tree/master/gstreamer-webrtc.

**Comment by ceyusa** [comment]
Are you looking for a complete coverage of the current C API?

Perhaps I'm misunderstanding, but isn't this issue a gstreamer-rs one?

**Comment by jdm** [comment]
Yes. I'm just listing work that needs to be done in order to add support in this repository, however.

**Comment by Manishearth** [comment]
We'd need to wrap it with stuff on this side too.

**Comment by jdm** [comment]
This is going to be necessary to support Hubs, which relies on the RTCDataChannel interface.

**Comment by ferjm** [comment]
#26752
