### ISSUE TITLE
Cannot receive webrtc streams from Servo

### ISSUE THREAD

**Issue by Manishearth** [servo/media#210]
When testing this please use https://github.com/servo/media/pull/208 . The bug is present without those changes, but is harder to test since the sink code is broken too.

For testing we're using the signalling server in https://github.com/jdm/gstwebrtc-demos/tree/nossl : `python -m SimpleHTTPServer` in the `js` folder, and `./simple-server.py` in the `signalling` folder. You'll need to remove the data channel code from webrtc.js

Currently we have three webrtc clients:

 - Firefox or any other browser, using its own webrtc implementation, pointed at `localhost:8000`
 - Servo, using servo-medias webrtc implementation, pointed at `localhost:8000` (with `dom.webrtc.enabled` set in prefs.json)
 - The simple_webrtc client, which emulates the javascript running on `localhost:8000`, and can be run against itself (`cargo ex simple_webrtc 8443` and then `cargo ex simple_webrtc 8443 <peer id>`)

With https://github.com/servo/media/pull/208 applied, running `simple_webrtc` against `simple_webrtc` works fine, as does running Firefox against `simple_webrtc`.

Servo does not. The servo side does not yet implement _playing_ streams, so we can expect that to not work, however it does support creating streams and sending them over webrtc, using the same servo-media code that simple_webrtc uses. When you run servo against simple_webrtc:

 - the negotiation runs fine
 - servo does indeed see the streams from simple_webrtc (as a pad-added signal)
 - simple_webrtc does _not_ receive the pad-added signal for servo's streams

**Comment by Manishearth** [comment]
Debugging the nicesrc and nicesink elements, both sides are receiving buffers normally. However, on dumping the Servo pipeline, the GstRtpSsrcDemux elements are connected to a jitter buffer, and on the servo-media side they are not.

**Comment by Manishearth** [comment]
Debugging the rtpssrc elements, I get the following log snippets for the servo side:

```
0:00:01.795456866 19888 0x7f96b401f280 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:712:gst_rtp_ssrc_demux_rtcp_chain:<rtpssrcdemux1> received RTCP of SSRC 7e2316cd
0:00:01.795495651 19888 0x7f96b401f280 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:278:find_or_create_demux_pad_for_ssrc:<rtpssrcdemux1> creating new pad for SSRC 7e2316cd
0:00:01.796575803 19888 0x7f96b401f280 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:712:gst_rtp_ssrc_demux_rtcp_chain:<rtpssrcdemux1> received RTCP of SSRC 7e2316cd
0:00:01.796731391 19888 0x7f96a4078800 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:625:gst_rtp_ssrc_demux_chain:<rtpssrcdemux1> received buffer of SSRC 7e2316cd
0:00:01.796978526 19888 0x7f96a4078800 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:625:gst_rtp_ssrc_demux_chain:<rtpssrcdemux1> received buffer of SSRC 7e2316cd
0:00:01.797016042 19888 0x7f96a4078800 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:625:gst_rtp_ssrc_demux_chain:<rtpssrcdemux1> received buffer of SSRC 7e2316cd
0:00:01.797040844 19888 0x7f96a4078800 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:625:gst_rtp_ssrc_demux_chain:<rtpssrcdemux1> received buffer of SSRC 7e2316cd
0:00:01.797063407 19888 0x7f96a4078800 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:625:gst_rtp_ssrc_demux_chain:<rtpssrcdemux1> received buffer of SSRC 7e2316cd
0:00:01.797086278 19888 0x7f96a4078800 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:625:gst_rtp_ssrc_demux_chain:<rtpssrcdemux1> received buffer of SSRC 7e2316cd
```

whereas the simple_webrtc side just sees the RTCP event over and over again:

```
0:00:01.071741793 19947 0x7f61540db540 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:712:gst_rtp_ssrc_demux_rtcp_chain:<rtpssrcdemux1> received RTCP of SSRC 3afb79b1
0:00:01.071784408 19947 0x7f61540db540 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:278:find_or_create_demux_pad_for_ssrc:<rtpssrcdemux1> creating new pad for SSRC 3afb79b1
0:00:01.449222975 19947 0x7f61540db540 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:712:gst_rtp_ssrc_demux_rtcp_chain:<rtpssrcdemux1> received RTCP of SSRC 3afb79b1
0:00:04.172509367 19947 0x7f61540db540 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:712:gst_rtp_ssrc_demux_rtcp_chain:<rtpssrcdemux1> received RTCP of SSRC 3afb79b1
0:00:09.493454588 19947 0x7f61540db540 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:712:gst_rtp_ssrc_demux_rtcp_chain:<rtpssrcdemux1> received RTCP of SSRC 3afb79b1
0:00:14.901417359 19947 0x7f61540db540 DEBUG           rtpssrcdemux gstrtpssrcdemux.c:712:gst_rtp_ssrc_demux_rtcp_chain:<rtpssrcdemux1> received RTCP of SSRC 3afb79b1
```

**Comment by Manishearth** [comment]
For some reason the overall servo pipeline is paused, too, but I can't tell why, and it only seems to be paused when I dump graph output (this doesn't happen on the other end). Its state is set to playing during answer creation.

**Comment by Manishearth** [comment]
Also, as far as I can tell, the _only_ difference between servo+localhost and simple_webrtc is that simple_webrtc attaches streams immediately after WebRtcController creation, whereas Servo waits for a getUserMedia promise to do it.


I tweaked simple_webrtc to add streams with a delay of a second and it still worked when played against itself.

**Comment by Manishearth** [comment]
Given that Servo on localhost and simple_webrtc should be running the same thing, I added logging to all events sent to the webrtc backend.

There is the difference that Servo attaches streams after receiving the offer, but I tweaked the JS to avoid that.

The other differences are:

 - When Servo gets the remote offer, it has an additional line of `a=fmtp:97 sprop-maxcapturerate=48000;sprop-stereo=0`, unlike simple_webrtc. I don't know where this came from, but I don't think it's relevant
 - The answer that Servo creates has an `a=recvonly` line. `simple_webrtc` has `a=framerate:30` and `a=sendrecv` . This seems pretty important.

**Comment by Manishearth** [comment]
Turns out that that the order that you link things to webrtcbin matters, and if you get it wrong things get set to recvonly mode. (Thanks @ystreet!)

A trivial "fix" for this is to invert the `add_stream` calls in simple_webrtc, or to reverse the MediaStream track order in Servo. This makes webrtc work just fine when running servo against simple_webrtc, but is obviously not the correct fix.

The correct fix is more complicated:
 - the webrtc backend object now has an m-line buffer and a stream buffer
 - Any time we `set_remote_description`, we should also update a local buffer containing the caps of each m-line (see [SDPMessage::get_media](http://sdroege.github.io/rustdoc/gstreamer/gstreamer_sdp/struct.SDPMessage.html#method.get_media)).
 - In the case of `set_remote_description` with an `offer`, we should unlink all streams (from the stream buffer) from webrtc, and reconnect them to the appropriate sinks, using caps-intersection between the m-line caps buffer and the stream caps. M-line buffer entries that are used up will be marked as such.
 - Any time we add a stream, we should store it in a the stream buffer, and attempt to add it to the sink using the m-line buffer and caps intersection. If we can't, just connect it directly, this will trigger renegotiation. This can happen both at the very beginning of the program when the offer-creator attaches streams, but also can happen if clients wish to dynamically add more streams to the connection.

This should be enough to make stuff work in a robust fashion, and should also automatically support [dynamically adding streams post negotiation](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/merge_requests/167) if we want to do that.

Eventually if we support RTP transceivers and friends this framework will need to be expanded a bit more, but not in a major way.

**Comment by Manishearth** [comment]
cc @jdm does the above look sensible to you?

**Comment by Manishearth** [comment]
Aside: the fact that the sink pad used must match the caps of the correspondingly numbered m-line seems to be something we should document in gstreamer-webrtc and add explicit handling for in the gstwebrtc examples. cc @nirbheek

(I might end up doing this myself if I get the chance)

**Comment by jdm** [comment]
Yep. Glad to understand what's going on better than before!

**Comment by Manishearth** [comment]
A potential flaw in the above solution: "just connect it directly" isn't quite right, since the following set of events can happen:

 - offer-er sets up an audio stream
 - answerer wants to do audio+video and decides to dynamically add an video stream too. it adds the video stream _first_
 - direct linkage picks first free sink pad, which is the audio pad. oops
 - audio gets connected to a request pad anyway


so I think what we should be doing in this case is using request pads? This isn't something we need to support immediately though, since gstreamer doesn't do dynamic streams yet anyway.

**Comment by Manishearth** [comment]
Blocked on https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/issues/189 . Without the ability to inspect the parsed m-line I can't do much here.
