### ISSUE TITLE
Build failed with "Unable to detect OpenSSL version"

### ISSUE THREAD

**Issue by georgeroman** [servo/media#231]
I'm trying to compile Servo Media locally but the build fails with the following message:
```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/george/servo/media/target/debug/build/openssl-e47a935d7c8ae2e2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/george/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

A few months ago I could build the project without getting any errors. I guess this happens due to the fact that I've recently updated my OpenSSL to version 1.1.1.

**Comment by jdm** [comment]
Try running `cargo update -p hyper-openssl` and see if that helps?

**Comment by jdm** [comment]
Whoops, that would help with Servo, but for this crate in particular I think you should try upgrade the websocket crate from 0.20 to 0.22.

**Comment by jdm** [comment]
In any case, upgrading the chain of dependencies such that we are using rust-openssl v0.10 instead of v0.9 should allow you to build with openssl v 1.1.1.

**Comment by georgeroman** [comment]
Updating `websocket` fixed  the build! Thank you for the help!
