### ISSUE TITLE
Deadlock in webrtc stream acquisition

### ISSUE THREAD

**Issue by Manishearth** [servo/media#249]
Running simple_webrtc has a deadlock in stream acquisition during `link_stream()`

https://github.com/servo/media/blob/ccbf63f1a43e1525ae07b0cb21d1ee6e419ea139/backends/gstreamer/webrtc.rs#L381

cc @ferjm

**Comment by ferjm** [comment]
Ugh, apologies for causing this regression. The webrtc example is not working for me, so I couldn't test it. Thanks for fixing it!

**Comment by Manishearth** [comment]
No biggie. What about the example doesn't work? Is it just the signaling
server? I can add comments on how you're supposed to set that up

**Comment by ferjm** [comment]
Last time I tried I was seeing this

```
0:00:22.921472000 11559 0x7fdb3f501490 ERROR glutils gstglutils.c:229:void gst_gl_element_propagate_display_context(GstElement *, GstGLDisplay *):<sink> Could not get GL display connection
```

And the example was crashing with a

```
[1] 11559 illegal hardware instruction GST_DEBUG=3 cargo ex simple_webrtc 8443.
```

I suspect there is something wrong with my gstreamer setup or something broken in webrtcbin and/or osxvideosink.

I am working on the support for multiple streams now, so I'll need to revisit this and try to make the example work for me.

**Comment by Manishearth** [comment]
Two things: 

 - does the example work if you change simple_webrtc to only use videotestsrc (currently one side opens a capture stream)?
 - does the local pipeline of `videotestsrc ! autovideosink` work? It may need videoconvert/etc elements in between.
