### ISSUE TITLE
Enhance the arguments handling in player example

### ISSUE THREAD

**Issue by ceyusa** [servo/media#259]
As @philn [pointed out](https://github.com/servo/media/pull/257#discussion_r282561592) we shall enhance the handling of arguments in the player test.

Perhaps using [clap](https://clap.rs/)

**Comment by brightly-salty** [comment]
I think this should be closed? It looks like it was fixed by PR#277. If not, and it's still an issue, I would be willing to attempt it.

**Comment by jdm** [comment]
Looks like it. Thanks!
