### ISSUE TITLE
Thread safety and driving model

### ISSUE THREAD

**Issue by Manishearth** [servo/media#27]
So currently we're not actually thread safe. There's an unsafe impl of Send/Sync on AudioGraphThread, which shouldn't exist.

We simultaneously need:

 - mutable access from the graph thread for things like adding nodes and play/pause
 - mutable access from gstreamer for running the graph.

This isn't good. We could solve it with locks, but that introduces two competing synchronization mechanisms. Instead I think we should have everything run by the graph thread (IIRC this was the original plan but we didn't really explore it), with gstreamer being isolated in a different thread requesting data.

The plan would be:

 - The graph thread is the only thing that touches the graph
 - when the sink needs data, it requests it from the graph thread, and waits
 - the graph thread processes incoming graph change messages, as well as incoming need_data messages. Whenever the source needs data, it sends it over.

We don't actually need a separate "gstreamer thread" setup, the graph thread can own the gstreamer sink and the need_data callbacks let this work asynchronously.

I'm a bit afraid that the render quantum of ~3ms may be affected by this model, though.

**Comment by Manishearth** [comment]
One alternate solution might be to let the sink own the graph, and send custom signals to it?

cc @sdroege what do you think?

I'm not quite sure how custom signals work here, and if they can guarantee that they're handled on the same thread.

Also there needs to be a decent way of sharing this graph between signal handlers i guess.

**Comment by sdroege** [comment]
With sink you mean from the WebAudio side, i.e. the GStreamer appsrc? There's no need to do anything from the need-data signal, or to block there when it is emitted. You can simply pass data to appsrc from any thread at any time you want, need-data only exists to make your life easier by having something telling you to provide new data whenever it would be needed.

As such, you can probably do one of the following, if I understand correctly how the WebAudio side of things works

1) Directly push buffers into appsrc whenever it becomes available from whatever thread you want, doing nothing with need-data
2) Have some kind of channel between WebAudio and appsrc, and simply take one item from the channel in every emission of the need-data signal. There's an enough-data signal that could be used to notify you that too much was produced, or you could use a bounded channel, or ...

The second seems to be more or less what you've implemented now, but maybe the `NeedsData` request from the appsrc to the WebAudio side is not actually needed if you already produce data there automatically whenever data is to be produced.

**Comment by ferjm** [comment]
Thank you @sdroege!

> Directly push buffers into appsrc whenever it becomes available from whatever thread you want, doing nothing with need-data

I guess we should use enough-data in this case to avoid excessive buffering, right? How does the need-data callback work after an enough-data callback? Is it fired after consuming all the buffered data or before that? If appsrc does not consume the entire buffer before firing the need-data callback, I think we can take this approach as it looks a bit cleaner.

**Comment by sdroege** [comment]
You can configure appsrc also to be blocking. It has an internal buffer (see the max-bytes property), and once that is full any further push call will block (and the enough-data signal is emitted every time more than max-bytes are provided). need-data is emitted whenever there is no data left at all anymore inside the appsrc buffer (or we go below min-percent).

See [here](https://github.com/GStreamer/gst-plugins-base/blob/9158f9f7eb5039ae67b3463f5dbac8d3ebb540ac/gst-libs/gst/app/gstappsrc.c#L1248-L1258) for need-data emissions (first case is below min-percent, second is empty). And [here](https://github.com/GStreamer/gst-plugins-base/blob/9158f9f7eb5039ae67b3463f5dbac8d3ebb540ac/gst-libs/gst/app/gstappsrc.c#L1828-L1832) for enough-data (this is whenever queued bytes is bigger than max-bytes)

**Comment by ferjm** [comment]
Nice!

We don't want to block the [rendering thread](https://webaudio.github.io/web-audio-api/#rendering-thread), so I guess we can simply check if we reached the max-bytes threshold with [get_current_level_bytes](https://sdroege.github.io/rustdoc/gstreamer/gstreamer_app/struct.AppSrc.html#method.get_current_level_bytes) ourselves to skip processing the graph in that case. Even if we reached that threshold we should continue processing messages coming from the [control thread](https://webaudio.github.io/web-audio-api/#control-thread).

**Comment by Manishearth** [comment]
Yeah the reason I block here is that we need some form of back pressure, otherwise the rendering thread will happily render into the future.

This same model could work without blocking if I use both a need data and enough data callback.

One question: how often is need_data called? I.e. if I fail to push data during the call back, will it get triggered again, immediately? Or is it only called a maximum of one time after each push_buffer call?

**Comment by ferjm** [comment]
Fixed by #29
