### ISSUE TITLE
Expose GL player hint to choose between GL_TEXTURE_EXTERNAL_OES and GL_TEXTURE_2D

### ISSUE THREAD

**Issue by jdm** [servo/media#291]
```
<xclaesse> ajeffrey: do you guys also support switching between GL_TEXTURE_EXTERNAL_OES and GL_TEXTURE_2D ?
<xclaesse> the latter is useful if you're using sw decoder like ffmpeg, or videotestsrc
```
We use the [default](https://github.com/servo/servo/blob/2981fe87ceeff4d5ccbba382c500d1eef9b1dfc4/components/script/dom/htmlmediaelement.rs#L223) for webrender's TextureTarget type right now. We should expose a hint through the media player's API to allow that code to choose the [right value](https://github.com/servo/webrender/blob/a27b83006271e944a2de0c34e496dba4e3c10119/webrender/src/device/gl.rs#L181-L184).

**Comment by ceyusa** [comment]
Right now we only support [GL_TEXTURE_2D](https://github.com/servo/media/blob/master/backends/gstreamer/render-unix/lib.rs#L213).
