### ISSUE TITLE
Support for BaseAudioContext.decodeAudioData

### ISSUE THREAD

**Issue by ferjm** [servo/media#41]
The decoding work needs to happen on a dedicated thread. We can probably use GStreamer [decodebin](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-decodebin.html) for this.

**Comment by philn** [comment]
Yep :)

**Comment by sdroege** [comment]
If you can shortly describe the API you need to implement for this and its expected behaviour then I can give you an idea how it could be implemented. Do you just need to somehow decode encoded audio data asynchronously? Synchronously? Should GStreamer fetch the data from somewhere or ...?

**Comment by philn** [comment]
Astnchronously. Data can be read from memory (with giostreamsrc for instance) or from a local file (if I remember correctly)... The code for this part of the backend was straight-forward to implement in WebKit.
