### ISSUE TITLE
Full OscillatorNode support

### ISSUE THREAD

**Issue by ferjm** [servo/media#42]
Right now we implement only the generation of sine waves, but there are other sine wave [types](https://webaudio.github.io/web-audio-api/#enumdef-oscillatortype) that we need to implement, including the [periodic waveform](https://webaudio.github.io/web-audio-api/#periodicwave). This is not a high priority at the moment though.

**Comment by jdm** [comment]
I am reserving this for a group of NCSU students to work on.

**Comment by jdm** [comment]
https://github.com/servo/media/blob/3292937b8bec7daed12b2f1b5739eb293610f5a2/audio/src/oscillator_node.rs#L120

**Comment by ferjm** [comment]
Part of this work was completed in #163. The remaining bits are tracked in https://github.com/servo/servo/issues/22364
