### ISSUE TITLE
Deinterleave decoded audio

### ISSUE THREAD

**Issue by ferjm** [servo/media#55]
With #54 in place, we can now deinterleave the decoded audio and create the AudioBuffer with the correct number of channels.

We can use [GStreamer's deinterleave](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-deinterleave.html) element for this.

**Comment by Manishearth** [comment]
We actually should manually deinterleave I think; because gstreamer doesn't know our block size and will deinterleave the full thing into separate blocks (which is ok too i guess)

**Comment by sdroege** [comment]
Yes, until full non-interleaved audio support lands in GStreamer. Soon :)

Deinterleaved element requires fully, sample by sample, interleaved audio and provides N separate mono streams
