### ISSUE TITLE
The switch to AppSrc broke Android example

### ISSUE THREAD

**Issue by ferjm** [servo/media#7]
We switched from BaseSrc to AppSrc in #4 and this broke the Android example. We get sound in desktop but no sound at all in Android. I see this in the logcat:

> 05-17 11:23:57.494  7738  8344 W GStreamer+basesrc: 0:00:08.982054176 0xd4ae4af0 gstbasesrc.c:3055:gst_base_src_loop:<appsrc0> error: Internal data stream error.
> 05-17 11:23:57.494  7738  8344 W GStreamer+basesrc: 0:00:08.982140165 0xd4ae4af0 gstbasesrc.c:3055:gst_base_src_loop:<appsrc0> error: streaming stopped, reason not-negotiated (-4)
> 05-17 11:23:57.494  7738  8344 W GStreamer+basetransform: 0:00:08.982345530 0xd4ae4af0 gstbasetransform.c:1355:gst_base_transform_setcaps:<audioconvert0> transform could not transform audio/x-raw, format=(string)F32LE, layout=(string)interleaved, rate=(int)48000, channels=(int)1 in anything we support
> 05-17 11:23:57.495  7738  8344 W GStreamer+basetransform: 0:00:08.982536884 0xd4ae4af0 gstbasetransform.c:1355:gst_base_transform_setcaps:<audioconvert0> transform could not transform audio/x-raw, format=(string)F32LE, layout=(string)interleaved, rate=(int)48000, channels=(int)1 in anything we support
> 05-17 11:23:57.495  7738  8344 W GStreamer+basetransform: 0:00:08.982646415 0xd4ae4af0 gstbasetransform.c:1355:gst_base_transform_setcaps:<audioconvert0> transform could not transform audio/x-raw, format=(string)F32LE, layout=(string)interleaved, rate=(int)48000, channels=(int)1 in anything we support
> 05-17 11:23:57.495  7738  8344 W GStreamer+audiobasesink: 0:00:08.982688968 0xd4ae4af0 gstaudiobasesink.c:1119:gst_audio_base_sink_wait_event:<autoaudiosink0-actual-sink-opensles> error: Sink not negotiated before eos event.

**Comment by philn** [comment]
Can you add an `audioresample` element in front of the `audioconvert` element? Those 2 often like to go together.

**Comment by ferjm** [comment]
I saw that in different examples, but I took a different approach in #8. Do you think it is still necessary to add the `audioresample` element?

**Comment by philn** [comment]
Yes I think it would still be good to have it because then you are sure there won't be any samplerate issue in any platform whatever the src/sink combination. And there won't be any performance bottleneck when the element works in pass-through.
