### ISSUE TITLE
merge rust-playground into media crate

### ISSUE THREAD

**Issue by ceyusa** [servo/media#73]
I would like to hear your opinion to merge [rust-playground](https://github.com/philn/rust-playground) into this crate.

The general idea is to simplify the merge to servo, provide a similar API for audio and video, and share common resources (I'm thinking, for example, the player objects or playbin).

**Comment by ferjm** [comment]
The plan for `<video>` and `<audio>` is to use `gst-player` in a similar way as [rust-playground](https://github.com/philn/rust-playground) does (with [some tweaks for WebAudio](https://github.com/servo/media/issues/43#issuecomment-394829268)), so we can definitely get some bits from there.

We should ideally maintain `servo-media` backend agnostic though, so we'd need to extract some of the logic from [here](https://github.com/philn/rust-playground/blob/master/src/player.rs) into traits.

**Comment by ceyusa** [comment]
well, the struct GstreamerPlayer, as is, cannot  be used as PlayerImpl trait object, since the trait has a function with a generic as parameter, breaking the rule of the trait object.

the options, as far as I see, are:

1. as I said before, decouple the observer methods
2. instead of passing a Generic, pass a box with the generic ... or a reference ??

**Comment by sdroege** [comment]
Associated types have to be provided for trait objects, e.g. `Box<PlayerImpl<Renderer=WhateverRenderer>>`. You could probably take a trait object as parameter to that function though?

**Comment by jdm** [comment]
Yes, accepting a `Box<FrameRenderer>` or `&FrameRenderer` argument would definitely work. For the associated type, the `Player` struct would need to implement `PlayerImpl` and `Player::new` (along with `create_player`) would need to accept a generic type that implements `FrameRenderer` in order to specify the associated type in the return type.

**Comment by ferjm** [comment]
> well, the struct GstreamerPlayer, as is, cannot be used as PlayerImpl trait object, since the trait has a function with a generic as parameter, breaking the rule of the trait object.

This is now fixed [here](https://github.com/ceyusa/media/commit/c1babe0a7a8de32dd1bd6c42c6232582489c4498). I've also rebased and updated everything to use the new multi-crate model.

**Comment by ceyusa** [comment]
> So the problem is that you can't use Box<PlayerImpl> because of the register_frame_renderer method in PlayerImpl that has a generic type? What if you add an associated type to the trait instead of using the generic on that method?

Yes, I ended up using an associated type :)
