### ISSUE TITLE
Set up TravisCI

### ISSUE THREAD

**Issue by jdm** [servo/media#80]
It should have a configuration that builds with android and build the dummy backend as well.

**Comment by jdm** [comment]
Consider https://github.com/servo/gecko-media/commit/cc78041f4d490adc2cb396e76ceda89a26438222 which enables a null audio backend for TravisCI on macOS.

**Comment by ferjm** [comment]
I don't have the permissions I need to setup Travis for this repo. @jdm do you know who could give me these permissions?

**Comment by Manishearth** [comment]
I'll set it up when I reach home.


Ideally we'd have tests that diff bytes with OfflineAudioContext.

**Comment by ferjm** [comment]
https://travis-ci.org/servo/media
